const fs = require('fs');
const path = require('path');

const attractions = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 8. GUJARAT
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Ahmedabad ──
  {
    id: "sabarmati-ashram",
    name: "Sabarmati Ashram (Gandhi Smarak Sangrahalaya)",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Ahmedabad",
    citySlug: "ahmedabad",
    type: "heritage",
    shortDescription: "Mahatma Gandhi's peaceful riverside headquarters from 1917 to 1930, launchpad of the historic 1930 Dandi Salt March.",
    longDescription: "Situated on the tranquil banks of the Sabarmati River. Established in 1917 by Mahatma Gandhi and Kasturba Gandhi. The compound houses Hriday Kunj (Gandhi's personal residence), Vinoba-Mira Kutir, the Magan Niwas spinning wheel institute, and Charles Correa's renowned open-air museum preserving original letters, spectacles, and spinning charkhas.",
    category: ["heritage", "history", "museums"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "2 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 23.0605, longitude: 72.5800 },
    image: "https://images.unsplash.com/photo-1598324789736-4861f89564a0?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Hriday Kunj (Mahatma Gandhi's personal writing room and desk)", "Original charkhas (spinning wheels) and handwritten letters", "Starting point of the 1930 historic Dandi Salt March", "Open-air museum designed by architect Charles Correa"],
    activities: ["Learning to spin cotton on a traditional wooden charkha", "Walking through the quiet riverfront gardens"],
    nearbyPlaces: ["Sabarmati Riverfront Promenade", "Adalaj Stepwell", "Calico Museum of Textiles"],
    travelTips: ["Visit in the early morning for peaceful reflection along the riverbank; entry is free"],
    accessibility: "Level walkways, shaded courtyards, and wheelchair accessible museum pavilions",
    familyFriendly: true,
    budgetLevel: "free",
    tags: ["sabarmati-ashram", "mahatma-gandhi", "dandi-march", "freedom-movement", "ahmedabad"],
    featured: true,
    priorityRank: 1
  },
  {
    id: "adalaj-stepwell",
    name: "Adalaj Stepwell (Adalaj Ni Vav)",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Ahmedabad",
    citySlug: "ahmedabad",
    type: "heritage",
    shortDescription: "Stunning 1498 five-storey subterranean stepwell fusing Solanki and Indo-Islamic carvings, built by Queen Rudadevi.",
    longDescription: "Built in 1498 by Queen Rudadevi in memory of King Rana Veer Singh. A brilliant specimen of Indian subterranean water architecture, descending five levels below ground into the cool water table. Intricately carved stone pillars, octagonal shafts, friezes of musicians, dancing women, and mythological motifs remain 5 degrees cooler than the surface heat.",
    category: ["heritage", "architecture", "history"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "1.5 hours",
    estimatedVisitTime: "2 hours",
    coordinates: { latitude: 23.1667, longitude: 72.5800 },
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Five subterranean storeys carved from buff sandstone", "Octagonal well shafts filtering dramatic rays of daylight", "Delicate floral Indo-Islamic and Hindu Solanki stone friezes", "Naturally climate-controlled underground atmosphere"],
    activities: ["Descending subterranean levels to photograph light beams", "Studying stone-carved Navagraha and Kalpavriksha panels"],
    nearbyPlaces: ["Gandhinagar Akshardham (15 km)", "Sabarmati Ashram"],
    travelTips: ["The best light for photography inside the deep octagonal shafts occurs between 11:00 AM and 2:00 PM when the sun shines directly down"],
    accessibility: "Requires walking down stone flights of stairs to reach lower subterranean platforms",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["adalaj-stepwell", "vav", "water-architecture", "solanki", "ahmedabad"],
    featured: true,
    priorityRank: 2
  },
  {
    id: "sidi-saiyyed-mosque",
    name: "Sidi Saiyyed Mosque (Tree of Life)",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Ahmedabad",
    citySlug: "ahmedabad",
    type: "heritage",
    shortDescription: "1573 mosque celebrated for its world-famous 'Tree of Life' stone lattice jali window, the global symbol of IIM Ahmedabad.",
    longDescription: "Constructed in 1573 by Sidi Saiyyed in the retinue of Bilal Jhajar Khan. World-renowned for its ten semi-circular stone windows filled with intricate pierced lattice jalis. The twin central jalis represent the 'Tree of Life' with intertwined banyan tree branches and palm foliage chiseled with gossamer delicacy from solid sandstone.",
    category: ["heritage", "architecture"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "45 minutes",
    estimatedVisitTime: "1 hour",
    coordinates: { latitude: 23.0270, longitude: 72.5810 },
    image: "https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Iconic 'Tree of Life' sandstone jali lattice window", "Official logo emblem of Indian Institute of Management Ahmedabad (IIMA)", "Gossamer filigree stone carving precision"],
    activities: ["Admiring and photographing the intricate lattice windows from the courtyard"],
    nearbyPlaces: ["Bhadra Fort", "Teen Darwaza", "Manek Chowk"],
    travelTips: ["Located in central Lal Darwaza; best viewed from the outside courtyard in afternoon sunlight when light filters through the foliage jali"],
    accessibility: "Level street and courtyard entry",
    familyFriendly: true,
    budgetLevel: "free",
    tags: ["tree-of-life", "sidi-saiyyed", "jali-lattice", "iim-ahmedabad", "heritage"],
    featured: false,
    priorityRank: 3
  },

  // ── Dwarka ──
  {
    id: "dwarkadhish-temple",
    name: "Dwarkadhish Temple (Jagat Mandir)",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Dwarka",
    citySlug: "dwarka",
    type: "spiritual",
    shortDescription: "One of the four supreme Char Dham pilgrimage shrines, a 2,200-year-old five-storey limestone temple dedicated to Lord Krishna 'King of Dwarka'.",
    longDescription: "Located at the tip of the Kathiawar peninsula on the Gomti River mouth. Built over 2,200 years ago by Krishna's great-grandson Vajranabha. The 78-meter high Chalukya-style spire is crowned by a 52-yard triangular silk flag (Dhvaja) depicting the sun and moon, hoisted five times daily by dedicated priests against Arabian Sea breezes.",
    category: ["spiritual", "heritage", "temples"],
    bestTimeToVisit: "October to March (Special during Janmashtami)",
    recommendedDuration: "2 - 3 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 22.2376, longitude: 68.9678 },
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["One of the sacred Char Dham abodes of Hinduism", "78-meter limestone spire supported by 72 carved sandstone pillars", "Changing of the 52-yard sacred silk flag (Dhvaja Arohan) five times daily", "Gomti Ghat and Sudama Setu suspension bridge directly adjacent"],
    activities: ["Darshan of Lord Dwarkadhish in royal regal attire", "Watching the ceremonial Dhvaja Arohan flag hoisting", "Crossing the Sudama Setu suspension bridge to Arabian Sea sands"],
    nearbyPlaces: ["Bet Dwarka", "Nageshwar Jyotirlinga", "Rukmini Devi Temple"],
    travelTips: ["Mobiles and electronic gadgets are strictly prohibited inside; deposit them in official security lockers before entry"],
    accessibility: "56 steps lead up to Swarga Dwar entry; elevator facilities available for seniors",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["char-dham", "dwarkadhish", "krishna-capital", "jagat-mandir", "spiritual"],
    featured: true,
    priorityRank: 1
  },

  // ── Somnath ──
  {
    id: "somnath-temple",
    name: "Shri Somnath Jyotirlinga Temple",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Somnath",
    citySlug: "somnath",
    type: "spiritual",
    shortDescription: "The first among the twelve sacred Jyotirlingas of Lord Shiva, rebuilt in majestic Maru-Gurjara style right on the roaring Arabian Sea shore.",
    longDescription: "Revered as 'The Eternal Shrine'. Located where the Saraswati, Hiranya, and Kapila rivers merge into the Arabian Sea. Repeatedly destroyed by foreign invaders and rebuilt seven times throughout history, its present grand form was consecrated in 1951 under Sardar Vallabhbhai Patel. The sea-facing arrow pillar (Baan Stambh) marks an unobstructed sea route directly to Antarctica.",
    category: ["spiritual", "heritage", "architecture", "temples"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "2 - 3 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 20.8880, longitude: 70.4010 },
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["First of the 12 sacred Jyotirlingas of Lord Shiva", "Grand Maru-Gurjara stone architecture right on the breaking sea waves", "Historic Baan Stambh (Arrow Pillar) pointing directly to the South Pole", "Evening 3D Sound and Light projection show narrated by Amitabh Bachchan"],
    activities: ["Darshan of the revered Somnath Jyotirlinga", "Watching the evening coastal Sound and Light Show", "Walking the paved sea promenade (Somnath Promenade)"],
    nearbyPlaces: ["Somnath Beach", "Triveni Sangam", "Bhalka Tirth"],
    travelTips: ["Strict security: no electronic devices, belts, or leather wallets allowed inside; lockers provided outside"],
    accessibility: "Wheelchair ramps throughout the vast sea-facing temple promenade",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["jyotirlinga", "somnath", "eternal-shrine", "arabian-sea", "spiritual"],
    featured: true,
    priorityRank: 1
  },

  // ── Kutch ──
  {
    id: "rann-of-kutch",
    name: "Great Rann of Kutch & White Desert (Dhordo)",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Kutch",
    citySlug: "kutch",
    type: "nature",
    shortDescription: "The world's largest salt desert spanning 7,500 sq km, transforming into a glowing white wonderland under the full moon during Rann Utsav.",
    longDescription: "A seasonal salt marsh located in the Thar Desert biosphere. During the dry winter months, the evaporated sea water leaves behind an unbroken, blinding-white expanse of pure crystalline salt that stretches to the horizon. Dhordo is the tent city hub for the world-famous Rann Utsav (November to February), featuring camel cart safaris, paramotoring, and Kutchi music.",
    category: ["nature", "culture", "adventure"],
    bestTimeToVisit: "November to February (Rann Utsav / Full Moon nights)",
    recommendedDuration: "2 - 3 days",
    estimatedVisitTime: "Full Day",
    coordinates: { latitude: 23.8333, longitude: 69.8333 },
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Vast endless crystalline white salt desert stretching to Pakistan border", "Magical silver full moon night vistas over the salt crust", "Rann Utsav luxury tent city with camel carts and cultural stages", "Paramotoring, ATV desert biking, and stargazing"],
    activities: ["Walking out onto the crunchy white salt flats at sunset", "Camel cart ride across the White Desert", "Paramotoring over the salt pans", "Shopping for Rogan art and Ajrakh block prints in artisan villages"],
    nearbyPlaces: ["Kala Dungar (Black Hill)", "Nirona Handicraft Village", "Dholavira Harappan Site"],
    travelTips: ["Visit during the 3 days around the monthly full moon (Purnima) when the desert glows silver; tourist permit required at Bhirandiyara checkpost"],
    accessibility: "Boardwalk and camel carts carry visitors out onto the firm salt crust",
    familyFriendly: true,
    budgetLevel: "moderate",
    tags: ["white-desert", "rann-utsav", "dhordo", "salt-desert", "kutch"],
    featured: true,
    priorityRank: 1
  },
  {
    id: "kala-dungar",
    name: "Kala Dungar (Black Hill) & Dattatreya Temple",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Kutch",
    citySlug: "kutch",
    type: "nature",
    shortDescription: "The highest point in Kutch at 458 meters, offering views where the White Desert merges with the blue sky, and wild jackal feeding rituals.",
    longDescription: "Located 97 km from Bhuj, Kala Dungar ('Black Hill') is the highest elevation in Kutch. From the summit viewing platform, the panoramic curve of the earth is visible where the blinding white salt desert meets the horizon and Pakistan border. Famous for the 400-year-old Dattatreya Temple, where priests feed wild jackals boiled rice and jaggery twice daily.",
    category: ["nature", "spiritual", "viewpoint"],
    bestTimeToVisit: "November to February",
    recommendedDuration: "2 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 23.9300, longitude: 69.8000 },
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Highest point in Kutch at 458 meters above sea level", "Unmatched panoramic view of the Great Rann merging with the sky", "400-year-old Lord Dattatreya hilltop temple", "Daily afternoon feeding of wild desert jackals by temple priests"],
    activities: ["Landscape photography from summit watchtowers", "Observing wild jackals arrive for temple feast"],
    nearbyPlaces: ["Dhordo White Desert (40 km)", "Khavda Craft Village"],
    travelTips: ["Visit in late afternoon to catch both the jackal feeding ritual and the breathtaking desert sunset"],
    accessibility: "Motorable road to the hilltop; short walk and steps to the viewing platform",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["kala-dungar", "black-hill", "dattatreya", "jackal-feeding", "kutch"],
    featured: false,
    priorityRank: 2
  },

  // ── Gir ──
  {
    id: "gir-national-park",
    name: "Gir National Park (Sasan Gir)",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Gir",
    citySlug: "gir",
    type: "wildlife",
    shortDescription: "The only natural habitat on planet Earth of the wild Asiatic Lion (Panthera leo leo), protected across 1,412 sq km of dry teak forest.",
    longDescription: "Once brought to the brink of extinction with barely 20 individuals surviving in the early 1900s, protected by the Nawab of Junagadh. Today, Gir is home to over 674 wild Asiatic Lions. Open-top Gypsy safaris take visitors through dry deciduous scrub and teak forests alongside leopards, chital, sambar, and the indigenous Maldhari pastoral tribes.",
    category: ["wildlife", "adventure", "nature"],
    bestTimeToVisit: "December to April",
    recommendedDuration: "2 days (2-3 safaris)",
    estimatedVisitTime: "Full Day",
    coordinates: { latitude: 21.1242, longitude: 70.8242 },
    image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Sole natural wild habitat of the majestic Asiatic Lion in the world", "Over 674 wild lions roaming free in open deciduous jungle", "Open-top 6-seater Gypsy safaris across 13 jungle routes", "Devalia Safari Park (Gir Interpretation Zone) for guaranteed sightings"],
    activities: ["Morning open Gypsy safari in core jungle", "Visiting Maldhari pastoralist tribal nesses (hamlets)", "Birdwatching for over 300 bird species"],
    nearbyPlaces: ["Somnath (45 km)", "Junagadh (60 km)"],
    travelTips: ["Book safari permits well in advance on the official Gujarat Forest Department portal; closed during monsoon (mid-June to mid-October)"],
    accessibility: "Open Gypsy safaris with boarding assistance",
    familyFriendly: true,
    budgetLevel: "moderate",
    tags: ["asiatic-lion", "gir-national-park", "sasan-gir", "wildlife", "safari"],
    featured: true,
    priorityRank: 1
  },

  // ── Patan ──
  {
    id: "rani-ki-vav",
    name: "Rani ki Vav (The Queen's Stepwell)",
    state: "Gujarat",
    stateSlug: "gujarat",
    city: "Patan",
    citySlug: "patan",
    type: "heritage",
    shortDescription: "UNESCO World Heritage 11th-century inverted temple stepwell built by Queen Udayamati, featuring over 800 exquisite Vishnu sculptures.",
    longDescription: "Built in 1063 AD by Queen Udayamati as a memorial to King Bhima I of the Chaulukya dynasty. Designed as an inverted subterranean temple highlighting the sanctity of water, descending seven storeys. Embellished with over 500 principal sculptures and 1,000 minor ones of Vishnu's Dashavatara avatars, Apsaras, and celestial nymphs chiselled with microscopic detail. Depicted on the reverse of India's ₹100 banknote.",
    category: ["heritage", "architecture", "history"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "2 - 3 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 23.8589, longitude: 72.1017 },
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["UNESCO World Heritage subterranean stepwell masterpiece", "Featured on the lavender-colored ₹100 Indian currency note", "Over 800 intricate sculptures of Vishnu, Sheshashayi, and Dashavatara", "Seven magnificent terraced subterranean pavilion levels"],
    activities: ["Studying the seven subterranean storeys of stone carvings", "Photographing the monument aligning with a ₹100 banknote", "Visiting adjacent Patan Patola double-ikat silk weaving workshops"],
    nearbyPlaces: ["Modhera Sun Temple (35 km)", "Patan Patola Heritage Museum"],
    travelTips: ["Bring a ₹100 Indian banknote to hold up against the monument for the iconic photo; visit nearby Patola weaving families to see real double-ikat sarees"],
    accessibility: "Paved garden pathways and viewing terraces at ground level; stone steps descend into the well",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["unesco", "rani-ki-vav", "stepwell", "100-rupee-note", "solanki", "patan"],
    featured: true,
    priorityRank: 1
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 9. MADHYA PRADESH
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Khajuraho ──
  {
    id: "khajuraho-temples",
    name: "Khajuraho Group of Monuments",
    state: "Madhya Pradesh",
    stateSlug: "madhya-pradesh",
    city: "Khajuraho",
    citySlug: "khajuraho",
    type: "heritage",
    shortDescription: "UNESCO World Heritage 10th-century Chandela temples celebrated for sublime Nagara spires and legendary erotic sculptural friezes.",
    longDescription: "Built between 950 and 1050 AD by the Chandela dynasty. Of the original 85 temples, 25 survive today across Western, Eastern, and Southern groups. Celebrated worldwide for their soaring Nagara-style spires simulating Mount Kailash, and thousands of masterwork stone sculptures depicting daily medieval life, musicians, celestial apsaras, and mithuna erotic art symbolizing human passion and divine cosmic union.",
    category: ["heritage", "architecture", "spiritual"],
    bestTimeToVisit: "October to March (Khajuraho Dance Festival in Feb)",
    recommendedDuration: "1 - 2 days",
    estimatedVisitTime: "Full Day",
    coordinates: { latitude: 24.8318, longitude: 79.9199 },
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Kandariya Mahadeva Temple with 84 miniature spires and 870 sculptures", "Lakshmana Temple with boar avatar Varaha monolithic statue", "Western Group of Temples set in manicured ASI lawns", "Annual Khajuraho Dance Festival staged against illuminated temples"],
    activities: ["Audio-guided exploration of the Western Temple Group", "Attending the evening Sound and Light Show", "Watching classical Bharatanatyam and Kathak during the February Dance Festival"],
    nearbyPlaces: ["Raneh Falls canyon", "Panna National Park (25 km)"],
    travelTips: ["The Western Group contains the finest and most intact temples; hire an authorized ASI guide to appreciate the spiritual symbology behind the erotic carvings"],
    accessibility: "Paved pathways through the Western Group lawns; temples stand on raised stone plinths reached by stairs",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["unesco", "khajuraho", "kandariya-mahadeva", "chandela", "nagara-architecture"],
    featured: true,
    priorityRank: 1
  },

  // ── Ujjain ──
  {
    id: "mahakaleshwar-temple",
    name: "Shri Mahakaleshwar Jyotirlinga & Mahakal Lok",
    state: "Madhya Pradesh",
    stateSlug: "madhya-pradesh",
    city: "Ujjain",
    citySlug: "ujjain",
    type: "spiritual",
    shortDescription: "One of the 12 sacred Jyotirlingas, the only south-facing (Dakshinmukhi) Shiva shrine, famous for the dawn Bhasma Aarti and 900-meter Mahakal Lok.",
    longDescription: "Located on the banks of the sacred Shipra River in the ancient prime meridian city of Ujjain (Avanti). Lord Shiva resides here as Mahakal, the Lord of Time and Death. The lingam is Dakshinmukhi (south-facing), a unique tantric attribute. World-famous for the sacred pre-dawn 4:00 AM Bhasma Aarti where the lingam is anointed with fresh sacred ash, and the newly unveiled 900-meter Mahakal Lok corridor with 200 mythological sculptures.",
    category: ["spiritual", "heritage", "temples"],
    bestTimeToVisit: "October to March (Special during Shravan & Kumbh Mela)",
    recommendedDuration: "3 - 4 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 23.1827, longitude: 75.7682 },
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Only south-facing (Dakshinmukhi) Jyotirlinga of Lord Shiva", "World-renowned pre-dawn 4:00 AM Bhasma Aarti ritual", "Grand newly constructed 900-meter 'Mahakal Lok' corridor with Rudrasagar lake", "Kumbh Mela (Simhastha) sacred pilgrimage destination"],
    activities: ["Participating in the sacred pre-dawn Bhasma Aarti", "Walking the illuminated 900-meter Mahakal Lok corridor at night", "Holy bath in the sacred Shipra River at Ram Ghat"],
    nearbyPlaces: ["Ram Ghat", "Kal Bhairav Temple", "Harsiddhi Temple"],
    travelTips: ["Advance online registration on the temple portal is mandatory for attending the 4:00 AM Bhasma Aarti; traditional dress strictly enforced (Dhoti for men, Saree for women)"],
    accessibility: "Electric golf carts and wheelchair ramps throughout the modern Mahakal Lok corridor",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["jyotirlinga", "mahakal", "bhasma-aarti", "mahakal-lok", "ujjain", "spiritual"],
    featured: true,
    priorityRank: 1
  },

  // ── Gwalior ──
  {
    id: "gwalior-fort",
    name: "Gwalior Fort & Man Mandir Palace",
    state: "Madhya Pradesh",
    stateSlug: "madhya-pradesh",
    city: "Gwalior",
    citySlug: "gwalior",
    type: "forts-palaces",
    shortDescription: "The 'Pearl of Indian Fortresses', an 8th-century hill citadel rising 300 feet, famous for vibrant turquoise glazed tile peacocks and Jain rock statues.",
    longDescription: "Described by Mughal Emperor Babur as 'the pearl amongst kingdoms of Hind'. Perched atop a sheer 3-km sandstone plateau. Highlights include Raja Man Singh Tomar's 15th-century Man Mandir Palace adorned with vibrant yellow ducks and blue turquoise tile mosaics, the 8th-century Teli Ka Mandir, the twin Sas Bahu temples, and the colossal rock-cut Jain Tirthankara statues lining the Gopachal Parvat slope.",
    category: ["forts-palaces", "heritage", "architecture"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "3 - 4 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 26.2307, longitude: 78.1695 },
    image: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Vibrant blue and yellow glazed ceramic tile peacocks on Man Mandir facade", "Colossal 58-foot rock-cut Jain Tirthankara statues along Gopachal hill slope", "Teli Ka Mandir (oldest monument in the fort with unique Dravidian roof)", "Sound and Light show narrated in Amitabh Bachchan's voice"],
    activities: ["Exploring the subterranean acoustic chambers of Man Mandir Palace", "Studying rock-cut Jain statues along the hill road", "Watching evening Sound and Light Show"],
    nearbyPlaces: ["Jai Vilas Palace", "Tomb of Tansen", "Sun Temple Gwalior"],
    travelTips: ["Vehicles can drive directly up to the summit parking via the western Urvai Gate, passing colossal rock-cut Jain statues"],
    accessibility: "Road access to summit; cobblestone palace courtyards",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["gwalior-fort", "pearl-of-fortresses", "man-mandir", "teli-ka-mandir", "heritage"],
    featured: true,
    priorityRank: 1
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 10. TELANGANA
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Hyderabad ──
  {
    id: "charminar",
    name: "Charminar",
    state: "Telangana",
    stateSlug: "telangana",
    city: "Hyderabad",
    citySlug: "hyderabad",
    type: "heritage",
    shortDescription: "The global icon of Hyderabad built in 1591 by Muhammad Quli Qutb Shah, a four-minaret triumphal monument surrounded by Laad Bazaar pearl stalls.",
    longDescription: "Erected in 1591 to commemorate the eradication of a deadly plague. Standing at the intersection of historic trade routes, this square granite-and-lime mortar monument features four grand arches facing the cardinal directions, surmounted by four 48.7-meter ornamental minarets. Houses Hyderabad's oldest surviving mosque on the upper terrace, encircled by the lacquer bangle shops of Laad Bazaar.",
    category: ["heritage", "architecture", "shopping"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "1.5 hours",
    estimatedVisitTime: "Evening",
    coordinates: { latitude: 17.3616, longitude: 78.4747 },
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Four 48.7-meter stucco carved minarets with spiral staircases", "Laad Bazaar famous for shimmering lacquer bangles and Hyderabadi pearls", "Mecca Masjid adjacent to the monument", "Irani Chai and Osmania biscuits at iconic Nimrah Cafe right beside Charminar"],
    activities: ["Climbing the first floor for views of old city bazaars", "Sipping hot Irani Chai at Nimrah Cafe", "Shopping for pearls and bangles in Laad Bazaar"],
    nearbyPlaces: ["Mecca Masjid", "Chowmahalla Palace", "Salar Jung Museum"],
    travelTips: ["Sip hot Irani Chai with maska bun at Nimrah Cafe & Bakery facing Charminar during golden hour"],
    accessibility: "Paved pedestrianized plaza surrounding the monument; climbing upper terrace requires spiral stairs",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["charminar", "hyderabad-symbol", "qutb-shahi", "laad-bazaar", "irani-chai"],
    featured: true,
    priorityRank: 1
  },
  {
    id: "golconda-fort",
    name: "Golconda Fort",
    state: "Telangana",
    stateSlug: "telangana",
    city: "Hyderabad",
    citySlug: "hyderabad",
    type: "forts-palaces",
    shortDescription: "Massive 16th-century diamond-trading citadel famed for acoustic marvels where a handclap at the entrance echoes 1 km uphill to the Bala Hissar pavilion.",
    longDescription: "The capital of the medieval Qutb Shahi Sultanate, world-renowned as the trade center for legendary diamonds from Kollur Mine (including the Koh-i-Noor, Hope Diamond, and Daria-i-Noor). Spanning 11 km of granite battlements, the fort is celebrated for its acoustic engineering: a clap at the outer Fateh Darwaza reverberates clearly at the Bala Hissar pavilion 1 km away.",
    category: ["forts-palaces", "heritage", "history"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "3 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 17.3833, longitude: 78.4011 },
    image: "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["Acoustic marvel: claps at Fateh Darwaza echo up to Bala Hissar summit", "Historic vault that once held the Koh-i-Noor diamond", "Breathtaking panoramic sunset view of Hyderabad skyline from the summit", "Evening Sound and Light Show narrated by Amitabh Bachchan"],
    activities: ["Testing the acoustic handclap phenomenon at the entrance dome", "Trekking 380 stone steps to the hilltop Bala Hissar royal pavilion", "Attending evening Sound and Light Show"],
    nearbyPlaces: ["Qutb Shahi Tombs (2 km)", "Taramati Baradari"],
    travelTips: ["Hire a licensed guide to demonstrate the acoustics and hidden water supply systems; wear comfortable walking shoes for the 380-step climb"],
    accessibility: "Requires climbing around 380 stone steps to reach the top pavilion; lower courtyards are level",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["golconda-fort", "koh-i-noor", "acoustics", "qutb-shahi", "hyderabad"],
    featured: true,
    priorityRank: 2
  },
  {
    id: "ramappa-temple",
    name: "Ramappa Temple (Rudreshwara Temple)",
    state: "Telangana",
    stateSlug: "telangana",
    city: "Warangal",
    citySlug: "warangal",
    type: "spiritual",
    shortDescription: "UNESCO World Heritage 13th-century Kakatiya temple built with floating bricks and earthquake-resistant sandbox foundations, named after its sculptor.",
    longDescription: "Constructed in 1213 AD by General Recharla Rudra under Kakatiya ruler Ganapati Deva. Uniquely named after its master sculptor Ramappa rather than the presiding deity. Built using lightweight 'floating bricks' that can float on water and earthquake-resistant 'sandbox' foundation technology. Features lustrous black basalt brackets carved with dancing celestial maidens (Madanikas).",
    category: ["spiritual", "heritage", "architecture"],
    bestTimeToVisit: "October to March",
    recommendedDuration: "2 hours",
    estimatedVisitTime: "Half Day",
    coordinates: { latitude: 18.2600, longitude: 79.9400 },
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    highlights: ["UNESCO World Heritage designation (inscribed 2021)", "Super-lightweight 'floating bricks' used in the temple vimana tower", "Mirror-polished black basalt carved Madanika dancing sculptures", "Historic Ramappa Lake water reservoir adjacent to temple"],
    activities: ["Studying Kakatiya stone carving precision", "Boat ride on adjacent Ramappa Lake"],
    nearbyPlaces: ["Warangal (65 km)", "Thousand Pillar Temple", "Laknavaram Lake"],
    travelTips: ["Located at Palampet (65 km from Warangal city); combine with a visit to Laknavaram hanging bridge lake on the same day"],
    accessibility: "Ramp and stone plinth access",
    familyFriendly: true,
    budgetLevel: "budget",
    tags: ["unesco", "ramappa-temple", "kakatiya", "floating-bricks", "warangal"],
    featured: true,
    priorityRank: 1
  }
];

console.log(`Gujarat, MP, and Telangana core attractions compiled: ${attractions.length}`);
fs.writeFileSync(path.join(__dirname, 'attractions_guj_mp_tg.json'), JSON.stringify(attractions, null, 2));
