const fs = require('fs');
const path = require('path');

const attractions = JSON.parse(fs.readFileSync(path.join(__dirname, 'all_attractions_list.json'), 'utf8'));

// Direct accurate Wikipedia titles or explicit search terms for all 198 attractions
const DIRECT_TITLES = {
  // ── Uttar Pradesh ──
  'taj-mahal': 'Taj Mahal',
  'agra-fort': 'Agra Fort',
  'itmad-ud-daulah': "Tomb of I'timad-ud-Daulah",
  'mehtab-bagh': 'Mehtab Bagh',
  'akbars-tomb': "Akbar's tomb",
  'fatehpur-sikri': 'Fatehpur Sikri',
  'kashi-vishwanath-temple': 'Kashi Vishwanath Temple',
  'dashashwamedh-ghat': 'Dashashwamedh Ghat',
  'assi-ghat': 'Assi Ghat',
  'manikarnika-ghat': 'Manikarnika Ghat',
  'sarnath': 'Dhamek Stupa',
  'ganga-riverfront': 'Ghats in Varanasi',
  'ramnagar-fort': 'Ramnagar Fort, Varanasi',
  'ram-mandir': 'Ram Mandir, Ayodhya',
  'hanuman-garhi': 'Hanuman Garhi, Ayodhya',
  'kanak-bhawan': 'Kanak Bhawan',
  'saryu-river-ghats': 'Saryu River',
  'ram-ki-paidi': 'Ram Ki Paidi',
  'bara-imambara': 'Bara Imambara',
  'chota-imambara': 'Chhota Imambara',
  'rumi-darwaza': 'Rumi Darwaza',
  'british-residency': 'The Residency, Lucknow',
  'hazratganj': 'Hazratganj',
  'ambedkar-memorial-park': 'Ambedkar Memorial Park',
  'krishna-janmabhoomi': 'Krishna Janmasthan Temple Complex',
  'banke-bihari-temple': 'Bankey Bihari Temple',
  'iskcon-vrindavan': 'Krishna Balaram Mandir',
  'prem-mandir': 'Prem Mandir, Vrindavan',
  'govardhan': 'Govardhan Hill',
  'kusum-sarovar': 'Kusum Sarovar',
  'triveni-sangam': 'Triveni Sangam',
  'allahabad-fort': 'Allahabad Fort',
  'anand-bhavan': 'Anand Bhavan',
  'khusro-bagh': 'Khusro Bagh',

  // ── Tamil Nadu ──
  'marina-beach': 'Marina Beach',
  'kapaleeshwarar-temple': 'Kapaleeshwarar Temple',
  'fort-st-george': 'Fort St. George, India',
  'san-thome-basilica': 'San Thome Basilica',
  'government-museum-chennai': 'Government Museum, Chennai',
  'besant-nagar-beach': 'Edward Elliot\'s Beach',
  'guindy-national-park': 'Guindy National Park',
  'valluvar-kottam': 'Valluvar Kottam',
  'shore-temple': 'Shore Temple',
  'pancha-rathas': 'Pancha Rathas',
  'arjunas-penance': 'Descent of the Ganges (relief)',
  'krishnas-butter-ball': "Krishna's Butterball",
  'mahabalipuram-beach': 'Mamallapuram',
  'meenakshi-amman-temple': 'Meenakshi Temple',
  'thirumalai-nayakkar-palace': 'Thirumalai Nayakkar Mahal',
  'gandhi-memorial-museum-madurai': 'Gandhi Memorial Museum, Madurai',
  'vaigai-river': 'Vaigai River',
  'alagar-koyil': 'Alagar Koyil',
  'ooty-lake': 'Ooty Lake',
  'botanical-garden-ooty': 'Government Botanical Gardens, Udagamandalam',
  'doddabetta-peak': 'Doddabetta',
  'rose-garden-ooty': 'Government Rose Garden, Ooty',
  'nilgiri-mountain-railway': 'Nilgiri Mountain Railway',
  'avalanche-lake': 'Avalanche Lake, India',
  'kodaikanal-lake': 'Kodaikanal Lake',
  'coakers-walk': "Coaker's Walk",
  'bryant-park': 'Bryant Park, Kodaikanal',
  'pillar-rocks': 'Pillar Rocks, Kodaikanal',
  'pine-forest-kodai': 'Kodaikanal',
  'guna-caves': 'Guna Caves',
  'ramanathaswamy-temple': 'Ramanathaswamy Temple',
  'pamban-bridge': 'Pamban Bridge',
  'dhanushkodi': 'Dhanushkodi',
  'ariyaman-beach': 'Ariyaman Beach',
  'apj-abdul-kalam-memorial': 'Dr. A. P. J. Abdul Kalam Desiya Ninaivagam',
  'brihadeeswarar-temple': 'Brihadisvara Temple',
  'thanjavur-palace': 'Thanjavur Maratha Palace',
  'saraswathi-mahal-library': 'Saraswathi Mahal Library',
  'vivekananda-rock-memorial': 'Vivekananda Rock Memorial',
  'thiruvalluvar-statue': 'Thiruvalluvar Statue',
  'kanyakumari-beach': 'Kanyakumari',
  'sunset-point-kanyakumari': 'Kanyakumari',
  'padmanabhapuram-palace': 'Padmanabhapuram Palace',

  // ── Karnataka ──
  'bangalore-palace': 'Bangalore Palace',
  'lalbagh-botanical-garden': 'Lal Bagh',
  'cubbon-park': 'Cubbon Park',
  'vidhana-soudha': 'Vidhana Soudha',
  'iskcon-bangalore': 'ISKCON Temple, Bangalore',
  'ub-city': 'UB City',
  'mysore-palace': 'Mysore Palace',
  'chamundi-hills': 'Chamundeshwari Temple',
  'brindavan-gardens': 'Brindavan Gardens',
  'st-philomenas-cathedral': "St. Philomena's Cathedral, Mysore",
  'mysuru-zoo': 'Mysore Zoo',
  'virupaksha-temple': 'Virupaksha Temple, Hampi',
  'vittala-temple': 'Vijayanagara architecture',
  'stone-chariot': 'Stone chariot, Hampi',
  'lotus-mahal': 'Lotus Mahal, Hampi',
  'elephant-stables': 'Elephant Stables, Hampi',
  'matanga-hill': 'Matanga Hill',
  'abbey-falls': 'Abbey Falls',
  'rajas-seat': "Raja's Seat",
  'dubare-elephant-camp': 'Dubare',
  'mandalpatti': 'Mandalpatti',
  'om-beach': 'Gokarna, India',
  'kudle-beach': 'Gokarna, India',
  'half-moon-beach': 'Gokarna, India',
  'mahabaleshwar-temple-gokarna': 'Mahabaleshwar Temple, Gokarna',
  'badami-cave-temples': 'Badami cave temples',
  'agastya-lake': 'Bhutanatha group of temples, Badami',

  // ── Andhra Pradesh ──
  'rk-beach-vizag': 'Ramakrishna Mission Beach',
  'kailasagiri-vizag': 'Kailasagiri',
  'ins-kurusura-submarine': 'INS Kurusura (S20)',
  'yarada-beach': 'Yarada Beach',
  'simhachalam-temple': 'Varaha Lakshmi Narasimha Temple, Simhachalam',
  'tirumala-venkateswara-temple': 'Venkateswara Temple, Tirumala',
  'kapila-theertham': 'Kapila Theertham',
  'sri-padmavathi-temple': 'Padmavathi Temple',
  'talakona-waterfalls': 'Talakona',
  'borra-caves': 'Borra Caves',
  'araku-valley-plantations': 'Araku Valley',
  'gandikota-fort': 'Gandikota',

  // ── Rajasthan ──
  'amber-fort': 'Amer Fort',
  'hawa-mahal': 'Hawa Mahal',
  'city-palace-jaipur': 'City Palace, Jaipur',
  'jantar-mantar-jaipur': 'Jantar Mantar, Jaipur',
  'jal-mahal': 'Jal Mahal',
  'nahargarh-fort': 'Nahargarh Fort',
  'jaigarh-fort': 'Jaigarh Fort',
  'city-palace-udaipur': 'City Palace, Udaipur',
  'lake-pichola': 'Lake Pichola',
  'jag-mandir': 'Jag Mandir',
  'sajjangarh-palace': 'Monsoon Palace',
  'fatehagar-lake': 'Fateh Sagar Lake',
  'fateh-sagar-lake': 'Fateh Sagar Lake',
  'mehrangarh-fort': 'Mehrangarh',
  'jaswant-thada': 'Jaswant Thada',
  'umaid-bhawan-palace': 'Umaid Bhawan Palace',
  'clock-tower-jodhpur': 'Ghanta Ghar (Jodhpur)',
  'jaisalmer-fort': 'Jaisalmer Fort',
  'patwon-ki-haveli': 'Patwon Ki Haveli',
  'sam-sand-dunes': 'Sam sand dunes',
  'gadisar-lake': 'Gadisar Lake',
  'desert-national-park': 'Desert National Park',
  'pushkar-lake': 'Pushkar Lake',
  'brahma-temple-pushkar': 'Brahma Temple, Pushkar',
  'pushkar-camel-fair': 'Pushkar Fair',
  'ranthambore-national-park': 'Ranthambore National Park',
  'ranthambore-fort': 'Ranthambore Fort',

  // ── Maharashtra ──
  'gateway-of-india': 'Gateway of India',
  'marine-drive': 'Marine Drive, Mumbai',
  'csmt-station': 'Chhatrapati Shivaji Maharaj Terminus',
  'elephanta-caves': 'Elephanta Caves',
  'colaba-causeway': 'Colaba Causeway',
  'siddhivinayak-temple': 'Siddhivinayak Temple, Mumbai',
  'juhu-beach': 'Juhu Beach',
  'bandra-worli-sea-link': 'Bandra–Worli Sea Link',
  'shaniwar-wada': 'Shaniwar Wada',
  'aga-khan-palace': 'Aga Khan Palace',
  'ajanta-caves': 'Ajanta Caves',
  'ellora-caves': 'Kailash Temple, Ellora',
  'bibi-ka-maqbara': 'Bibi Ka Maqbara',
  'daulatabad-fort': 'Daulatabad Fort',

  // ── West Bengal ──
  'victoria-memorial': 'Victoria Memorial, Kolkata',
  'howrah-bridge': 'Howrah Bridge',
  'dakshineswar-kali-temple': 'Dakshineswar Kali Temple',
  'indian-museum-kolkata': 'Indian Museum, Kolkata',
  'tiger-hill-darjeeling': 'Tiger Hill, Darjeeling',
  'darjeeling-himalayan-railway': 'Darjeeling Himalayan Railway',
  'batasia-loop': 'Batasia Loop',
  'sundarbans-national-park': 'Sundarbans National Park',

  // ── Gujarat ──
  'sabarmati-ashram': 'Sabarmati Ashram',
  'adalaj-stepwell': 'Adalaj Stepwell',
  'sidi-saiyyed-mosque': 'Sidi Saiyyed Mosque',
  'dwarkadhish-temple': 'Dwarkadhish Temple',
  'somnath-temple': 'Somnath temple',
  'rann-of-kutch': 'Great Rann of Kutch',
  'kala-dungar': 'Kalo Dungar',
  'gir-national-park': 'Gir National Park',
  'rani-ki-vav': 'Rani ki Vav',

  // ── Madhya Pradesh ──
  'khajuraho-temples': 'Khajuraho Group of Monuments',
  'mahakaleshwar-temple': 'Mahakaleshwar Jyotirlinga',
  'gwalior-fort': 'Gwalior Fort',

  // ── Telangana ──
  'charminar': 'Charminar',
  'golconda-fort': 'Golconda',
  'ramappa-temple': 'Ramappa Temple',

  // ── Kerala ──
  'chinese-fishing-nets': 'Chinese fishing nets',
  'mattancherry-palace': 'Mattancherry Palace',
  'tea-gardens-munnar': 'Munnar',
  'eravikulam-national-park': 'Eravikulam National Park',
  'alappuzha-backwaters': 'Kerala backwaters',
  'periyar-national-park': 'Periyar National Park',
  'varkala-cliff': 'Varkala Beach',

  // ── Bihar ──
  'mahabodhi-temple': 'Mahabodhi Temple',
  'nalanda-mahavihara': 'Nalanda',

  // ── Odisha ──
  'konark-sun-temple': 'Konark Sun Temple',
  'jagannath-temple-puri': 'Jagannath Temple, Puri',

  // ── Punjab ──
  'golden-temple': 'Golden Temple',
  'wagah-border': 'Wagah-Attari border ceremony',

  // ── Uttarakhand ──
  'rishikesh-ganga-aarti': 'Triveni Ghat',
  'har-ki-pauri': 'Har Ki Pauri',
  'naini-lake': 'Nainital Lake',
  'jim-corbett-national-park': 'Jim Corbett National Park',
  'kedarnath-temple': 'Kedarnath Temple',
  'badrinath-temple': 'Badrinath Temple'
};

console.log('Direct titles configured:', Object.keys(DIRECT_TITLES).length, 'of 198 attractions');
